### ISSUE TITLE
Adjacent selectors are highlighted as errors

### ISSUE THREAD

**Issue by tryashtar** [Arcensoth/language-mcfunction#24]
![image](https://user-images.githubusercontent.com/26075577/60836072-fed90780-a181-11e9-949a-bb20d80cdd98.png)
![image](https://user-images.githubusercontent.com/26075577/60836132-2b8d1f00-a182-11e9-8cca-569f95a84339.png)

These commands are valid in both java and bedrock, but appear as an error/weirdly highlighted here

**Comment by Arcensoth** [comment]
this is going to be fun to think about

**Comment by Arcensoth** [comment]
This is related to #23  in that, without context of the command, it is difficult to know whether these are selectors or just garbled strings.

Additional rambling follows...

I don't immediately see a solution that highlights adjacent selectors, because this type of syntax isn't actually allowed anywhere. As far as the in-game command parser is concerned, what follows `say` is just a greedy all-consuming string. But of course without context it's impossible to know that we are within a `say` command in the first place.

One work-around would be stop these tokens from being highlighted as an error simply by providing a fallback that captures any type of whitespace-delimited string of characters. The problem with this solution is that it would leave us without the error highlighting for every place we're using real selector arguments.

Another work-around is to add a hard-coded case for `say` (or any command that uses a greedy string), but given that this is a version-agnostic grammar it's a last resort at best. I already do this for `execute run` and I still feel dirty for it to this day. But considering that most of these bugs are with commands that use greedy strings, this might just be the solution I go with.

**Comment by Arcensoth** [comment]
See #25
