### ISSUE TITLE
Blockstates (+ optional NBT) without namespace highlight as error

### ISSUE THREAD

**Issue by tryashtar** [Arcensoth/language-mcfunction#26]
![image](https://user-images.githubusercontent.com/26075577/62407279-ceaf3980-b572-11e9-9e96-6ab143b32018.png)
![image](https://user-images.githubusercontent.com/26075577/62418021-ada32300-b61c-11e9-94ec-f92061a51640.png)

**Comment by Arcensoth** [comment]
IIRC this is :works_as_intended: for the version-agnostic grammar because of how difficult (and potentially expensive) it would be to forward-detect blocks without namespaces, since namespaces are one of their primary defining features.

This is a comment people bring up often though, so next time I go bug-busting I'll take another look and see if I can't come up with a reasonable, light-weight solution.

**Comment by Arcensoth** [comment]
See #18 (reopened)

**Comment by Arcensoth** [comment]
Never mind, I'm going to continue using this issue as a point-of-reference for block predicates specifically.

**Comment by Arcensoth** [comment]
(from #18)

> Support is viable for block predicates with a block state mapping present, otherwise it's ambiguous with an NBT path.

![image](https://user-images.githubusercontent.com/1885643/65302501-5c59df00-db49-11e9-92ec-825576b1536d.png)

**Comment by Arcensoth** [comment]
For reference, here's what it looked like before this change:

![image](https://user-images.githubusercontent.com/1885643/65302681-e144f880-db49-11e9-8bef-5eea15dd9500.png)

**Comment by Arcensoth** [comment]
Implemented in e017d027e1a3fb921da7e7ad272bbca226fd1199
