### ISSUE TITLE
Is there a way to toggle line comments?

### ISSUE THREAD

**Issue by dragon3025** [Arcensoth/language-mcfunction#29]
Usually you can use ctrl+/ and shift+alt+a, but that doesn't work in this. Is there a way to do this?

**Comment by Arcensoth** [comment]
@dragon3025 Did you find the answer somewhere else? Because that sounds like an issue with VSCode itself.

**Comment by dragon3025** [comment]
I think I realized this extension does is coloring for mcfunction files, the intellisense functions I have comes from [Datapack Helper Plus (MCF)](https://github.com/SPGoding/datapack-language-server) and the toggle line comments function that isn't working would come from their extension. I hadn't asked this question there yet though.

**Comment by Arcensoth** [comment]
@dragon3025 You're correct that this extension's scope is limited to syntax highlighting, however it does [define line comments](https://github.com/Arcensoth/language-mcfunction/blob/master/language-configuration.json#L4) as part of the standard VSCode language settings (default: `ctrl + /`).

That being said, I can't recall this extension ever having any issues related to keyboard shortcuts. I don't think it has anything to do with DHP either, because I've been using both extensions side-by-side for a while now without any issue. The author of DHP also recommends this extension for syntax highlighting, so I'm sure they've tested it as well.

I'd recommend going through your other extensions as well as VSCode keyboard shortcuts and language options to make sure everything is configured properly.

**Comment by dragon3025** [comment]
I checked all of it, and nothing was out of place, but strangely it's working now.
