### ISSUE TITLE
Is it supposed to just make everything pink?

### ISSUE THREAD

**Issue by BeepBeepImASheepie** [Arcensoth/language-mcfunction#37]
All this does for me is highlight everything with hot pink.

**Comment by Arcensoth** [comment]
No, and I haven't heard of this issue before either. Which editor are you using? Do you have other datapack-related extensions enabled that would conflict with the highlighting? Ensure you're files end with `.mcfunction` and you have the `mcfunction` language selected for those files. (Do not choose `mcfunction-snapshot` because that is an experimental grammar.)

**Comment by BeepBeepImASheepie** [comment]
> No, and I haven't heard of this issue before either. Which editor are you using? Do you have other datapack-related extensions enabled that would conflict with the highlighting? Ensure your files end with `.mcfunction` and you have the `mcfunction` language selected for those files. (As opposed to `mcfunction-snapshot` which is an incomplete experimental grammar.)

sublime text 3, no other extensions, they all end with mcfunction, and yes it is mcfunction language.

**Comment by BeepBeepImASheepie** [comment]
> > No, and I haven't heard of this issue before either. Which editor are you using? Do you have other datapack-related extensions enabled that would conflict with the highlighting? Ensure your files end with `.mcfunction` and you have the `mcfunction` language selected for those files. (As opposed to `mcfunction-snapshot` which is an incomplete experimental grammar.)
> 
> sublime text 3, no other extensions, they all end with mcfunction, and yes it is mcfunction language.

OOPS SORRY I DID IT WRONG. Its working now i didnt have the correct file open when i tested sorry.
