### ISSUE TITLE
"Commands" underlined in json

### ISSUE THREAD

**Issue by xhendrikg** [Arcensoth/language-mcfunction#44]
![grafik](https://user-images.githubusercontent.com/69456711/114313563-4c249e80-9af7-11eb-9598-f60421b27668.png)
Vscode thinks that its an command but its a json and i also use [] and ""

**Comment by Arcensoth** [comment]
Your command is invalid because it contains unescaped quotes. The `"` before `/trigger` marks the end of the string, so everything after that token is rendered invalid:

```mcfunction
tellraw @a ["use "/trigger foo" to do the thing"]
```

You need to escape the quotes:

```mcfunction
tellraw @a ["use \"/trigger foo\" to do the thing"]
```

Also: language-mcfunction only provides highlighting and is not the source of the squiggles/underlines. If the issue persists after correcting the quotes: you need to disable other extensions first to confirm that this is indeed an issue with the highlighter (as per #40).
