### ISSUE TITLE
Inconsistant Color Highlighting with scores

### ISSUE THREAD

**Issue by AnimeWatcherX** [Arcensoth/language-mcfunction#49]
So I have been using this for a while (on mac, if that matters), and I noticed that highlighting score names is quite inconsistant. So things like score names in commands like
`execute as @a[scores={test=1}]` will highlight the score called test correctly
but then in things such as `execute if score global test matches 1` then It will not color the fake player or the score.

This score highlighting issue is also present in the /scoreboard command aswell.

Player names in specific like my user name, Anime_Watcher2, or Animewatcher2, will not get highlighted either.

![Screen Shot 2021-07-02 at 8 00 36 PM](https://user-images.githubusercontent.com/86859519/124337362-2fd15480-db70-11eb-9fda-9276c8933578.png)
![Screen Shot 2021-07-02 at 8 00 11 PM](https://user-images.githubusercontent.com/86859519/124337358-25af5600-db70-11eb-81e2-8a2bc5419693.png)
![Screen Shot 2021-07-02 at 7 55 05 PM](https://user-images.githubusercontent.com/86859519/124337211-75d9e880-db6f-11eb-8c77-6847fe9dc3f2.png)
![Screen Shot 2021-07-02 at 8 01 21 PM](https://user-images.githubusercontent.com/86859519/124337382-49729c00-db70-11eb-852e-4aa00e7a76dd.png)

Edit for another thing:
Quotes are not properly highlighted in color either
![Screen Shot 2021-07-02 at 8 03 34 PM](https://user-images.githubusercontent.com/86859519/124337445-a40bf800-db70-11eb-9c72-de292c062a97.png)

**Comment by Arcensoth** [comment]
In general, the inconsistencies with certain types of arguments are a result of the version-agnostic ("context-free") grammar classifying these tokens differently based on the characters they are composed of. The reason for this behaviour is that the grammar doesn't have context of which command is being used; nor does it have context of which selector argument is being used. Without that information, all it can do is guess what type of token is present based on the characters present. Score holders in particular accept a wide-range of possibilities so it's difficult and sometimes impossible for the grammar to determine the token class accurately.

This is one of the trade-offs of having a version-agnostic grammar: the highlighting is less accurate in context-sensitive cases, but in return it can support the vast majority of syntax for any prior or current version of the game. (This is critical for multi-version support and in particular GitHub's highlighting.)

As for the `gbtimer` inside the selector being highlighted differently from the `gbtimer` in scoreboard commands: this is because the keys inside of selector mappings are classified differently from the literals we see as command arguments. Keep in mind the grammar doesn't know that these are scores at all - I expect advancements and/or criteria to be highlighted similarly. (From what I recall, the grammar starts parsing a generalized "mapping" when it encounters braces as the value of a selector argument.)

**Comment by Arcensoth** [comment]
So the TLDR here is that this is working as intended for the reasons listed earlier. (For the version-agnostic grammar anyway; the version-specific grammars will be able to identify things like scores with high accuracy if/when I ever finish that project.)

As for the edit about quotes: looks fine to me, other than maybe it being white but that's probably the colour theme. Quoted strings are classified with quotation marks and their contents all in one. The colour theme is responsible for assigning the final, actual colour. You're welcome to provide more information in a separate issue, though. 👍
