### ISSUE TITLE
Finding Language Specific Grammer is like trying to navigate a maze

### ISSUE THREAD

**Issue by AnimeWatcherX** [Arcensoth/language-mcfunction#51]
I have been using this for a while (in sublime) and honestly its amazing, however I am trying to switch to the version specific instead of the version agnostic.
Little did I know that I would spend 2 hours looking though the files and online trying to figure out where/how I can do this.
There are files about customization, but they dont tell you how to enable the version specific in the first place.
So if possible, I request that is made more clear where you switch between the version specific, and version agnostic.

Edit: I still have no idea how to go to/enable the version specific grammar.

**Comment by Arcensoth** [comment]
This is very much intentional as the version-specific grammars are incomplete and only intended to be used by developers/contributors:

> The version-specific grammars are currently under heavy development. These grammars are incomplete and experimental. They do not yet support the same feature set as the version-agnostic grammar. Please only use these grammars if you intend to contribute in some form, such as pull requests, bug reports, or general feedback. **To use the version-specific grammars, you will need to build them and configure the extension yourself.**

(via: https://github.com/Arcensoth/language-mcfunction#configuring-the-version-specific-grammars)

I recently removed the version-specific "snapshot" grammar from the editor configuration, because there was the occasional person who tried to use it - thinking it was complete - and then submitted a bug report about it not working.

I'll go ahead and also mention that I don't know if or when the version-specific grammars will be complete and supported. The version-agnostic grammar is mature and relatively stable, while the version-specific grammars have yet to progress beyond an experiment. For development with the Java Edition of the game, there are tools like [SPYGlass](https://github.com/SPYGlassMC/SPYGlass) to help with more accurate highlighting and error reporting in the editor via language server protocol.
