### ISSUE TITLE
[REQUEST] Autocompletion

### ISSUE THREAD

**Issue by JoeJoeTV** [Arcensoth/language-mcfunction#9]
Adding Autocompletion for commands,id's,etc would be very useful.

**Comment by Arcensoth** [comment]
I'm considering this for the version-specific grammars based on the game's commands.json. But because autocompeltion requires a language server, it may be some time before I get there.

There's a langserver project in-the-works for 1.13+ you might be interested in: https://github.com/Levertion/mcfunction-langserver

**Comment by JoeJoeTV** [comment]
Thanks for replying so fast, but I'm interested what exactly a language server is and where you can get the commands.json and registries.json, can you extract them from the class files in the jar?

**Comment by Arcensoth** [comment]
A language server is a type of extension for VSCode, required for almost any language features beyond basic syntax highlighting: https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

As for Minecraft's generated data: yes, it's been available since 1.13 snapshots. There's some good stuff in there, you can have a look here: https://github.com/Arcensoth/mcdata

**Comment by Arcensoth** [comment]
Closing this issue because the requested feature is already planned for the version-specific grammars.

**Comment by Arcensoth** [comment]
Closing the issue permanently after deciding that language-mcfunction will focus on language grammar definitions and syntax highlighting, and that LSP features are out-of-scope. Here are some other extensions for mcfunction and datapack LSP support:

- https://github.com/SPGoding/datapack-language-server
- https://github.com/Levertion/mcfunction-langserver
